### ISSUE TITLE
DeconvolutionWithCalibration Error

### ISSUE THREAD

**Issue by SitoTorres** [elitaone/Methyl-SNP-seq#2]
Hello, I keep encountering this error when trying to run the Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration python script:

/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py:180: RuntimeWarning: invalid value encountered in double_scalars
  [dic_Likelihood[key]*dic_Priorprobability[key]/Evidence for key in ['A', 'C', 'G', 'T']]))
Traceback (most recent call last):
  File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/__main__.py", line 281, in <module>
    args.reference, args.smp, args.vcf, args.pathBowtie2, args.pathSamtools, args.pathBedtools)
  File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/__main__.py", line 242, in main
    BaseCalibration.main('{}_deconvoluted_R1.compareBase.txt'.format(name), '{}_R2.compareBase.txt'.format(name), name)
  File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py", line 262, in main
    ls_return = pool.map(Calculateprobability, range(0, cycle+1))
  File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/pathos/multiprocessing.py", line 139, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 572, in get
    raise self._value
ValueError: cannot convert float NaN to integer

--------------------

I am using Python Python 2.7.15, pandas==0.24.2 and pathos==0.2.8

Any idea what the problem might be?

Thank you so much!

Sito

**Comment by elitaone** [comment]
Hi Sito,

Thank you for exploring our method.
It seems that you've encountered an issue related to non-integer counts, leading to a pandas error.
The error message you provided doesn't offer clear insights, making it a bit challenging for me to pinpoint the exact problem.

Could you share your original data (fastq files) for analysis? This way, I can take a closer look and figure out what's causing the issue.

Please feel free to contact me at this email for quicker responses: ***@***.***

Sincerely,
Bo Yan
New England Biolabs
________________________________
From: Sito Torres-Garcia ***@***.***>
Sent: Thursday, February 22, 2024 8:53 AM
To: elitaone/Methyl-SNP-seq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [elitaone/Methyl-SNP-seq] DeconvolutionWithCalibration Error (Issue #2)


Hello, I keep encountering this error when trying to run the Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration python script:

/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py:180: RuntimeWarning: invalid value encountered in double_scalars
[dic_Likelihood[key]*dic_Priorprobability[key]/Evidence for key in ['A', 'C', 'G', 'T']]))
Traceback (most recent call last):
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 281, in
args.reference, args.smp, args.vcf, args.pathBowtie2, args.pathSamtools, args.pathBedtools)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 242, in main
BaseCalibration.main('{}_deconvoluted_R1.compareBase.txt'.format(name), '{}_R2.compareBase.txt'.format(name), name)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py", line 262, in main
ls_return = pool.map(Calculateprobability, range(0, cycle+1))
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/pathos/multiprocessing.py", line 139, in map
return _pool.map(star(f), zip(*args)) # chunksize
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 253, in map
return self.map_async(func, iterable, chunksize).get()
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 572, in get
raise self._value
ValueError: cannot convert float NaN to integer

________________________________

I am using Python Python 2.7.15, pandas==0.24.2 and pathos==0.2.6

Any idea what the problem might be?

Thank you so much!

Sito

**Comment by SitoTorres** [comment]
Hi Bo,

Thank you so much for your quick response!!

Here are the fastq’s I am trying to run (they are a subset of the original file), I am just trying to get the pipeline to run!

<https://www.dropbox.com/scl/fo/t7n8nfd5giu8571rt4upm/h?rlkey=0fshfh81v8hbp2dyvv5rwhx9c&dl=0>
[opengraph-content-icon-folder-dropbox-landscape.png]
STG_Methyl-SNP-seq_data<https://www.dropbox.com/scl/fo/t7n8nfd5giu8571rt4upm/h?rlkey=0fshfh81v8hbp2dyvv5rwhx9c&dl=0>
dropbox.com<https://www.dropbox.com/scl/fo/t7n8nfd5giu8571rt4upm/h?rlkey=0fshfh81v8hbp2dyvv5rwhx9c&dl=0>

Original sample was mouse genomic DNA. This has been trimmed already, so in theory it should be ready for deconvolution.

Thank you so much!

Let me know if you need any other info please. I really appreciate your help!

Best
Sito


On 22 Feb 2024, at 14:49, elitaone ***@***.***> wrote:


Hi Sito,

Thank you for exploring our method.
It seems that you've encountered an issue related to non-integer counts, leading to a pandas error.
The error message you provided doesn't offer clear insights, making it a bit challenging for me to pinpoint the exact problem.

Could you share your original data (fastq files) for analysis? This way, I can take a closer look and figure out what's causing the issue.

Please feel free to contact me at this email for quicker responses: ***@***.***

Sincerely,
Bo Yan
New England Biolabs
________________________________
From: Sito Torres-Garcia ***@***.***>
Sent: Thursday, February 22, 2024 8:53 AM
To: elitaone/Methyl-SNP-seq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [elitaone/Methyl-SNP-seq] DeconvolutionWithCalibration Error (Issue #2)


Hello, I keep encountering this error when trying to run the Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration python script:

/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py:180: RuntimeWarning: invalid value encountered in double_scalars
[dic_Likelihood[key]*dic_Priorprobability[key]/Evidence for key in ['A', 'C', 'G', 'T']]))
Traceback (most recent call last):
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 281, in
args.reference, args.smp, args.vcf, args.pathBowtie2, args.pathSamtools, args.pathBedtools)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 242, in main
BaseCalibration.main('{}_deconvoluted_R1.compareBase.txt'.format(name), '{}_R2.compareBase.txt'.format(name), name)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py", line 262, in main
ls_return = pool.map(Calculateprobability, range(0, cycle+1))
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/pathos/multiprocessing.py", line 139, in map
return _pool.map(star(f), zip(*args)) # chunksize
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 253, in map
return self.map_async(func, iterable, chunksize).get()
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 572, in get
raise self._value
ValueError: cannot convert float NaN to integer

________________________________

I am using Python Python 2.7.15, pandas==0.24.2 and pathos==0.2.6

Any idea what the problem might be?

Thank you so much!

Sito

**Comment by SitoTorres** [comment]
P.S. Just to clarify, I am actually using pathos==0.2.8 (and not 0.2.6) cause I couldn’t get 0.2.6 to install!!

Hope this is not creating the issue.

Thank you
Sito

On 22 Feb 2024, at 14:58, Sito Torres-Garcia ***@***.***> wrote:

Hi Bo,

Thank you so much for your quick response!!

Here are the fastq’s I am trying to run (they are a subset of the original file), I am just trying to get the pipeline to run!

<https://www.dropbox.com/scl/fo/t7n8nfd5giu8571rt4upm/h?rlkey=0fshfh81v8hbp2dyvv5rwhx9c&dl=0>
<opengraph-content-icon-folder-dropbox-landscape.png>
STG_Methyl-SNP-seq_data<https://www.dropbox.com/scl/fo/t7n8nfd5giu8571rt4upm/h?rlkey=0fshfh81v8hbp2dyvv5rwhx9c&dl=0>
dropbox.com<https://www.dropbox.com/scl/fo/t7n8nfd5giu8571rt4upm/h?rlkey=0fshfh81v8hbp2dyvv5rwhx9c&dl=0>

Original sample was mouse genomic DNA. This has been trimmed already, so in theory it should be ready for deconvolution.

Thank you so much!

Let me know if you need any other info please. I really appreciate your help!

Best
Sito


On 22 Feb 2024, at 14:49, elitaone ***@***.***> wrote:


Hi Sito,

Thank you for exploring our method.
It seems that you've encountered an issue related to non-integer counts, leading to a pandas error.
The error message you provided doesn't offer clear insights, making it a bit challenging for me to pinpoint the exact problem.

Could you share your original data (fastq files) for analysis? This way, I can take a closer look and figure out what's causing the issue.

Please feel free to contact me at this email for quicker responses: ***@***.***

Sincerely,
Bo Yan
New England Biolabs
________________________________
From: Sito Torres-Garcia ***@***.***>
Sent: Thursday, February 22, 2024 8:53 AM
To: elitaone/Methyl-SNP-seq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [elitaone/Methyl-SNP-seq] DeconvolutionWithCalibration Error (Issue #2)


Hello, I keep encountering this error when trying to run the Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration python script:

/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py:180: RuntimeWarning: invalid value encountered in double_scalars
[dic_Likelihood[key]*dic_Priorprobability[key]/Evidence for key in ['A', 'C', 'G', 'T']]))
Traceback (most recent call last):
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 281, in
args.reference, args.smp, args.vcf, args.pathBowtie2, args.pathSamtools, args.pathBedtools)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 242, in main
BaseCalibration.main('{}_deconvoluted_R1.compareBase.txt'.format(name), '{}_R2.compareBase.txt'.format(name), name)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py", line 262, in main
ls_return = pool.map(Calculateprobability, range(0, cycle+1))
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/pathos/multiprocessing.py", line 139, in map
return _pool.map(star(f), zip(*args)) # chunksize
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 253, in map
return self.map_async(func, iterable, chunksize).get()
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 572, in get
raise self._value
ValueError: cannot convert float NaN to integer

________________________________

I am using Python Python 2.7.15, pandas==0.24.2 and pathos==0.2.6

Any idea what the problem might be?

Thank you so much!

Sito

**Comment by elitaone** [comment]
Hi Sito,
I'll review your data and reach out to you once I have insights, hopefully early next week.
Bo

________________________________

**Comment by SitoTorres** [comment]
Thank you so much Bo! I really appreciate your help!

Best,
Sito

On 22 Feb 2024, at 16:19, elitaone ***@***.***> wrote:


Hi Sito,
I'll review your data and reach out to you once I have insights, hopefully early next week.
Bo

________________________________

**Comment by elitaone** [comment]
Hi Sito,

I've identified the problem with your testing data.

I tested using 50% of your fastq reads for base calibration (--percent 0.5). With a small dataset (normally unusual for human), there were instances of zero counts, causing a division by zero error or log by zero error for Bayesian Inference, as seen in cycle2 shown below.

Reads cycle2 counting:
                Base_A  Base_C  Base_G  Base_T   sum
        REF_A    1855       0       0       1  1856
        REF_C       0    1973       0       1  1974
        REF_G     226       0     676       0   902
        REF_T       0       1       0    2258  2259

I've addressed this by updating the BaseCalibration.py script to skip the base calibration step if there isn't enough data for calculation: in the BaseCalibration.probability report labeled 'NA' in Quality Score column. In such cases, it will utilize the quality score of Read1 for the corresponding base in deconvoluted reads.

The script has been modified, and you can test it out. I have confirmed this change does not change the counting if you have a larger dataset as we did for the paper.

I will utilize a larger dataset for base calibration to enhance accuracy, and you can control the percentage using the --percent option, as detailed in the README file. Or if you have a small dataset, you might consider skipping base calibration and using the DeconvolutionConversion_v2.py script instead.

Let me know if this resolves the issue for you or if you have any further questions.

PS: Note that pathos has discontinued installation for Python 2, so I'll be updating my scripts to Python 3 soon.

Bo

________________________________
From: Sito Torres-Garcia ***@***.***>
Sent: Thursday, February 22, 2024 8:53 AM
To: elitaone/Methyl-SNP-seq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [elitaone/Methyl-SNP-seq] DeconvolutionWithCalibration Error (Issue #2)


Hello, I keep encountering this error when trying to run the Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration python script:

/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py:180: RuntimeWarning: invalid value encountered in double_scalars
[dic_Likelihood[key]*dic_Priorprobability[key]/Evidence for key in ['A', 'C', 'G', 'T']]))
Traceback (most recent call last):
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 281, in
args.reference, args.smp, args.vcf, args.pathBowtie2, args.pathSamtools, args.pathBedtools)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 242, in main
BaseCalibration.main('{}_deconvoluted_R1.compareBase.txt'.format(name), '{}_R2.compareBase.txt'.format(name), name)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py", line 262, in main
ls_return = pool.map(Calculateprobability, range(0, cycle+1))
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/pathos/multiprocessing.py", line 139, in map
return _pool.map(star(f), zip(*args)) # chunksize
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 253, in map
return self.map_async(func, iterable, chunksize).get()
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 572, in get
raise self._value
ValueError: cannot convert float NaN to integer

________________________________

I am using Python Python 2.7.15, pandas==0.24.2 and pathos==0.2.6

Any idea what the problem might be?

Thank you so much!

Sito

**Comment by SitoTorres** [comment]
Hi Bo,

Thank you SO much for looking into this. I truly appreciate your help!!

Unfortunately our cluster went down during the weekend and I can’t test this at the moment, but I will do as soon as it is back online and I will let you know!

Thank you so much again for taking the time!

Best wishes,
Sito

PS. It would be great to have the scripts running on Python 3! Thank you!

On 25 Feb 2024, at 00:57, elitaone ***@***.***> wrote:


Hi Sito,

I've identified the problem with your testing data.

I tested using 50% of your fastq reads for base calibration (--percent 0.5). With a small dataset (normally unusual for human), there were instances of zero counts, causing a division by zero error or log by zero error for Bayesian Inference, as seen in cycle2 shown below.

Reads cycle2 counting:
Base_A Base_C Base_G Base_T sum
REF_A 1855 0 0 1 1856
REF_C 0 1973 0 1 1974
REF_G 226 0 676 0 902
REF_T 0 1 0 2258 2259

I've addressed this by updating the BaseCalibration.py script to skip the base calibration step if there isn't enough data for calculation: in the BaseCalibration.probability report labeled 'NA' in Quality Score column. In such cases, it will utilize the quality score of Read1 for the corresponding base in deconvoluted reads.

The script has been modified, and you can test it out. I have confirmed this change does not change the counting if you have a larger dataset as we did for the paper.

I will utilize a larger dataset for base calibration to enhance accuracy, and you can control the percentage using the --percent option, as detailed in the README file. Or if you have a small dataset, you might consider skipping base calibration and using the DeconvolutionConversion_v2.py script instead.

Let me know if this resolves the issue for you or if you have any further questions.

PS: Note that pathos has discontinued installation for Python 2, so I'll be updating my scripts to Python 3 soon.

Bo

________________________________
From: Sito Torres-Garcia ***@***.***>
Sent: Thursday, February 22, 2024 8:53 AM
To: elitaone/Methyl-SNP-seq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [elitaone/Methyl-SNP-seq] DeconvolutionWithCalibration Error (Issue #2)


Hello, I keep encountering this error when trying to run the Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration python script:

/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py:180: RuntimeWarning: invalid value encountered in double_scalars
[dic_Likelihood[key]*dic_Priorprobability[key]/Evidence for key in ['A', 'C', 'G', 'T']]))
Traceback (most recent call last):
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 281, in
args.reference, args.smp, args.vcf, args.pathBowtie2, args.pathSamtools, args.pathBedtools)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 242, in main
BaseCalibration.main('{}_deconvoluted_R1.compareBase.txt'.format(name), '{}_R2.compareBase.txt'.format(name), name)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py", line 262, in main
ls_return = pool.map(Calculateprobability, range(0, cycle+1))
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/pathos/multiprocessing.py", line 139, in map
return _pool.map(star(f), zip(*args)) # chunksize
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 253, in map
return self.map_async(func, iterable, chunksize).get()
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 572, in get
raise self._value
ValueError: cannot convert float NaN to integer

________________________________

I am using Python Python 2.7.15, pandas==0.24.2 and pathos==0.2.6

Any idea what the problem might be?

Thank you so much!

Sito

**Comment by SitoTorres** [comment]
Hi Bo,

I just got this (DeconvolutionWithCalibration) to run successfully!

Thank you so much for looking into this so promptly, for identifying the problem, and for finding a solution! I really appreciate your help.

Looking forward to doing more analyses and trying the Motif Calling pipeline etc. very soon!

Thanks again!

Best wishes,
Sito



On 26 Feb 2024, at 11:11, Sito Torres-Garcia ***@***.***> wrote:

Hi Bo,

Thank you SO much for looking into this. I truly appreciate your help!!

Unfortunately our cluster went down during the weekend and I can’t test this at the moment, but I will do as soon as it is back online and I will let you know!

Thank you so much again for taking the time!

Best wishes,
Sito

PS. It would be great to have the scripts running on Python 3! Thank you!

On 25 Feb 2024, at 00:57, elitaone ***@***.***> wrote:


Hi Sito,

I've identified the problem with your testing data.

I tested using 50% of your fastq reads for base calibration (--percent 0.5). With a small dataset (normally unusual for human), there were instances of zero counts, causing a division by zero error or log by zero error for Bayesian Inference, as seen in cycle2 shown below.

Reads cycle2 counting:
Base_A Base_C Base_G Base_T sum
REF_A 1855 0 0 1 1856
REF_C 0 1973 0 1 1974
REF_G 226 0 676 0 902
REF_T 0 1 0 2258 2259

I've addressed this by updating the BaseCalibration.py script to skip the base calibration step if there isn't enough data for calculation: in the BaseCalibration.probability report labeled 'NA' in Quality Score column. In such cases, it will utilize the quality score of Read1 for the corresponding base in deconvoluted reads.

The script has been modified, and you can test it out. I have confirmed this change does not change the counting if you have a larger dataset as we did for the paper.

I will utilize a larger dataset for base calibration to enhance accuracy, and you can control the percentage using the --percent option, as detailed in the README file. Or if you have a small dataset, you might consider skipping base calibration and using the DeconvolutionConversion_v2.py script instead.

Let me know if this resolves the issue for you or if you have any further questions.

PS: Note that pathos has discontinued installation for Python 2, so I'll be updating my scripts to Python 3 soon.

Bo

________________________________
From: Sito Torres-Garcia ***@***.***>
Sent: Thursday, February 22, 2024 8:53 AM
To: elitaone/Methyl-SNP-seq ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [elitaone/Methyl-SNP-seq] DeconvolutionWithCalibration Error (Issue #2)


Hello, I keep encountering this error when trying to run the Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration python script:

/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py:180: RuntimeWarning: invalid value encountered in double_scalars
[dic_Likelihood[key]*dic_Priorprobability[key]/Evidence for key in ['A', 'C', 'G', 'T']]))
Traceback (most recent call last):
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 281, in
args.reference, args.smp, args.vcf, args.pathBowtie2, args.pathSamtools, args.pathBedtools)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/main.py", line 242, in main
BaseCalibration.main('{}_deconvoluted_R1.compareBase.txt'.format(name), '{}_R2.compareBase.txt'.format(name), name)
File "/home/torres01/software/Methyl-SNP-seq-main/Read_Processing/DeconvolutionWithCalibration/src/BaseCalibration.py", line 262, in main
ls_return = pool.map(Calculateprobability, range(0, cycle+1))
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/pathos/multiprocessing.py", line 139, in map
return _pool.map(star(f), zip(*args)) # chunksize
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 253, in map
return self.map_async(func, iterable, chunksize).get()
File "/home/torres01/mambaforge/envs/methyl_snp_seq/lib/python2.7/site-packages/multiprocess/pool.py", line 572, in get
raise self._value
ValueError: cannot convert float NaN to integer

________________________________

I am using Python Python 2.7.15, pandas==0.24.2 and pathos==0.2.6

Any idea what the problem might be?

Thank you so much!

Sito
